from __future__ import annotations

from typing import Dict

from router.models import Stage

LEXICAL_PHRASE_TABLE: tuple[tuple[str, Stage, int, str], ...] = (
    # Operator
    ("decide", Stage.OPERATOR, 4, "decide"),
    ("deciding", Stage.OPERATOR, 4, "deciding"),
    ("decision", Stage.OPERATOR, 4, "decision"),
    ("choose", Stage.OPERATOR, 4, "choose"),
    ("choosing", Stage.OPERATOR, 4, "choosing"),
    ("recommend", Stage.OPERATOR, 4, "recommend"),
    ("recommendation", Stage.OPERATOR, 4, "recommendation"),
    ("make a call", Stage.OPERATOR, 5, "make a call"),
    ("what should we do", Stage.OPERATOR, 5, "what should we do"),
    ("now", Stage.OPERATOR, 2, "now"),
    ("this week", Stage.OPERATOR, 2, "this week"),
    ("immediate", Stage.OPERATOR, 3, "immediate"),
    ("commit", Stage.OPERATOR, 3, "commit"),
    ("next move", Stage.OPERATOR, 4, "next move"),
    ("tradeoff", Stage.OPERATOR, 4, "tradeoff"),
    ("best option now", Stage.OPERATOR, 6, "best option now"),
    ("select", Stage.OPERATOR, 4, "select"),
    ("selecting", Stage.OPERATOR, 4, "selecting"),
    ("select between options", Stage.OPERATOR, 5, "select between options"),
    ("choose between", Stage.OPERATOR, 5, "choose between"),
    ("time pressure", Stage.OPERATOR, 3, "time pressure"),
    # Epistemic
    ("unknown", Stage.EPISTEMIC, 4, "unknown"),
    ("unknowns", Stage.EPISTEMIC, 4, "unknowns"),
    ("unclear", Stage.EPISTEMIC, 4, "unclear"),
    ("unresolved", Stage.EPISTEMIC, 4, "unresolved"),
    ("what is missing", Stage.EPISTEMIC, 5, "what is missing"),
    ("what do we not know", Stage.EPISTEMIC, 5, "what do we not know"),
    ("support", Stage.EPISTEMIC, 3, "support"),
    ("evidence", Stage.EPISTEMIC, 4, "evidence"),
    ("verify", Stage.EPISTEMIC, 4, "verify"),
    ("rigor", Stage.EPISTEMIC, 3, "rigor"),
    ("proof", Stage.EPISTEMIC, 3, "proof"),
    ("confidence", Stage.EPISTEMIC, 2, "confidence"),
    ("are you sure", Stage.EPISTEMIC, 4, "are you sure"),
    ("can't tell", Stage.EPISTEMIC, 4, "can't tell"),
    ("can't tell what kind", Stage.EPISTEMIC, 5, "can't tell what kind"),
    ("don't know what kind", Stage.EPISTEMIC, 5, "don't know what kind"),
    ("hard to characterize", Stage.EPISTEMIC, 4, "hard to characterize"),
    ("can't characterize", Stage.EPISTEMIC, 4, "can't characterize"),
    ("can't identify", Stage.EPISTEMIC, 4, "can't identify"),
    ("can't name it yet", Stage.EPISTEMIC, 4, "can't name it yet"),
    # Synthesis
    ("strongest interpretation", Stage.SYNTHESIS, 10, "strongest interpretation"),
    ("strongest frame", Stage.SYNTHESIS, 10, "strongest frame"),
    ("what this actually is", Stage.SYNTHESIS, 10, "what this actually is"),
    ("many signals", Stage.SYNTHESIS, 4, "many signals"),
    ("no center", Stage.SYNTHESIS, 4, "no center"),
    ("parts are legible", Stage.SYNTHESIS, 5, "parts are legible"),
    ("whole organizing logic is missing", Stage.SYNTHESIS, 6, "whole organizing logic is missing"),
    ("fragments but no spine", Stage.SYNTHESIS, 6, "fragments but no spine"),
    ("fragments are understood", Stage.SYNTHESIS, 5, "fragments are understood"),
    ("spine is still missing", Stage.SYNTHESIS, 6, "spine is still missing"),
    ("hidden spine", Stage.SYNTHESIS, 4, "hidden spine"),
    ("what this really is", Stage.SYNTHESIS, 4, "what this really is"),
    ("unify", Stage.SYNTHESIS, 4, "unify"),
    ("coherent picture", Stage.SYNTHESIS, 5, "coherent picture"),
    ("coherent", Stage.SYNTHESIS, 2, "coherent"),
    # Adversarial
    ("weakest points", Stage.ADVERSARIAL, 5, "weakest points"),
    ("weak spots", Stage.ADVERSARIAL, 5, "weak spots"),
    ("strongest objections", Stage.ADVERSARIAL, 6, "strongest objections"),
    ("vulnerabilities", Stage.ADVERSARIAL, 6, "vulnerabilities"),
    ("failure modes", Stage.ADVERSARIAL, 6, "failure modes"),
    ("where this breaks", Stage.ADVERSARIAL, 5, "where this breaks"),
    ("break under pressure", Stage.ADVERSARIAL, 6, "break under pressure"),
    ("how this could fail", Stage.ADVERSARIAL, 6, "how this could fail"),
    ("attack this frame", Stage.ADVERSARIAL, 7, "attack this frame"),
    ("stress points", Stage.ADVERSARIAL, 5, "stress points"),
    ("what would break this frame", Stage.ADVERSARIAL, 6, "what would break this frame"),
    ("what would break it", Stage.ADVERSARIAL, 5, "what would break it"),
    # Exploration
    ("possibility", Stage.EXPLORATION, 3, "possibility"),
    ("brainstorm", Stage.EXPLORATION, 4, "brainstorm"),
    ("explore", Stage.EXPLORATION, 2, "explore"),
    ("alternatives", Stage.EXPLORATION, 3, "alternatives"),
    ("option space", Stage.EXPLORATION, 3, "option space"),
    ("open possibilities", Stage.EXPLORATION, 4, "open possibilities"),
)

NEGATED_CLOSURE_PHRASES: Dict[str, int] = {
    "do not decide": 4,
    "don't decide": 4,
    "not decide yet": 4,
    "do not recommend": 4,
    "don't recommend": 4,
    "do not choose": 4,
    "don't choose": 4,
    "do not make a call": 5,
    "not ready to decide": 4,
}
